export type AnatomyFact = { id: number; fact: string; topic: string };

// Facts are grouped by topic, then flattened and interleaved so consecutive
// days show different regions. No admin panel, no database — purely static.
const BY_TOPIC: Record<string, string[]> = {
  "General Anatomy": [
    "The liver can regenerate even after losing around 70% of its tissue.",
    "The adult human body contains 206 bones, but a newborn starts with about 270.",
    "Skin is the largest organ of the body, covering roughly 1.5–2 m² in adults.",
    "The femur is the longest and strongest bone in the human body.",
    "The stapes in the middle ear is the smallest bone, about 3 mm long.",
    "Cartilage has no blood supply and receives nutrients by diffusion.",
    "Red bone marrow produces about 2 million red blood cells every second.",
    "There are more than 600 named skeletal muscles in the human body.",
    "Ligaments connect bone to bone; tendons connect muscle to bone.",
    "Roughly 60% of adult body weight is water.",
    "Synovial joints are the most mobile joints and contain a lubricating synovial fluid.",
    "Fascia is a continuous sheet of connective tissue that links the whole body.",
    "The anatomical position is standing erect, facing forward, palms turned anteriorly.",
    "A sesamoid bone develops within a tendon — the patella is the largest example.",
    "Lymph nodes filter lymph and are the first stop for metastasising tumour cells.",
    "The body has roughly 100,000 km of blood vessels.",
    "Elastic cartilage keeps the auricle and epiglottis flexible yet shape-retaining.",
    "Periosteum supplies bone with nutrients and is richly innervated — hence bone pain.",
    "Compact bone forms the shaft of long bones; spongy bone fills the epiphyses.",
    "Hyaline cartilage covers articular surfaces and reduces friction to near zero.",
    "Dermatomes map a strip of skin supplied by a single spinal nerve root.",
    "An anastomosis is a connection between vessels that provides collateral flow.",
    "End arteries have no anastomoses, so occlusion causes infarction.",
    "Serous membranes such as pleura and peritoneum secrete lubricating fluid.",
    "Bursae are fluid-filled sacs that reduce friction near joints.",
    "The axial skeleton has 80 bones; the appendicular skeleton has 126.",
    "Bone remodels continuously — the adult skeleton is replaced roughly every 10 years.",
    "Wolff's law: bone adapts its architecture to the loads placed on it.",
    "Fibrous joints such as skull sutures allow almost no movement.",
    "Deep fascia forms intermuscular septa that divide limbs into compartments.",
    "Aponeuroses are flattened tendons that attach muscle to broad surfaces.",
    "Body temperature is regulated mainly by the hypothalamus at around 37°C.",
    "Sweat glands number roughly 2–4 million across the skin.",
    "The thickest skin is on the palms and soles; the thinnest on the eyelids.",
    "Blood accounts for about 7–8% of total body weight.",
  ],
  "Upper Limb": [
    "The clavicle is the most commonly fractured bone in the body.",
    "The clavicle is the first bone to ossify and the last to complete ossification.",
    "The rotator cuff is formed by supraspinatus, infraspinatus, teres minor and subscapularis.",
    "The axillary nerve wraps the surgical neck of the humerus and is at risk in fractures.",
    "The radial nerve runs in the spiral groove — mid-shaft humeral fracture causes wrist drop.",
    "The 'funny bone' sensation is the ulnar nerve behind the medial epicondyle.",
    "The median nerve is compressed in carpal tunnel syndrome beneath the flexor retinaculum.",
    "There are 8 carpal bones arranged in two rows of four.",
    "The scaphoid is the most commonly fractured carpal bone and risks avascular necrosis.",
    "The anatomical snuffbox is bounded by the tendons of EPL, EPB and APL.",
    "Biceps brachii is the most powerful supinator of the forearm.",
    "Brachialis is the main flexor of the elbow regardless of forearm position.",
    "The brachial plexus arises from spinal roots C5 to T1.",
    "Erb's palsy affects the upper trunk (C5–C6) giving the 'waiter's tip' posture.",
    "Klumpke's palsy affects C8–T1 and produces a claw hand.",
    "The cephalic vein runs in the deltopectoral groove to reach the axillary vein.",
    "The median cubital vein is the classic site for venepuncture.",
    "The thumb has only two phalanges; every other digit has three.",
    "Lumbricals of the hand flex the MCP joints and extend the IP joints.",
    "The ulnar nerve supplies all intrinsic hand muscles except LOAF muscles.",
    "The radial artery pulse is felt lateral to flexor carpi radialis at the wrist.",
    "Allen's test checks the patency of the radial and ulnar arteries.",
    "The glenohumeral joint sacrifices stability for the greatest range of motion.",
    "Serratus anterior palsy from long thoracic nerve injury causes winging of the scapula.",
    "The carrying angle of the elbow is greater in females than males.",
    "Dupuytren's contracture is a thickening of the palmar aponeurosis.",
    "The axilla is a pyramidal space transmitting vessels and nerves to the limb.",
    "Supraspinatus initiates the first 15° of shoulder abduction.",
  ],
  "Lower Limb": [
    "The femur can withstand loads of about 1,700 kg before fracturing.",
    "The patella is the largest sesamoid bone in the body.",
    "The sciatic nerve is the thickest nerve, roughly the width of a thumb.",
    "The great saphenous vein is the longest vein in the body.",
    "The ACL prevents anterior displacement of the tibia on the femur.",
    "The medial meniscus is attached to the MCL, making it more often injured.",
    "The 'unhappy triad' involves the ACL, MCL and medial meniscus.",
    "The femoral triangle is bounded by the inguinal ligament, sartorius and adductor longus.",
    "NAVEL: nerve, artery, vein, empty space, lymphatics from lateral to medial in the femoral triangle.",
    "Sartorius is the longest muscle in the human body.",
    "The common fibular nerve winds around the fibular neck — injury causes foot drop.",
    "The tibia bears weight; the fibula mainly provides muscle attachment.",
    "There are 26 bones in each foot — a quarter of all the bones in the body.",
    "The calcaneus is the largest tarsal bone and forms the heel.",
    "The Achilles tendon is the strongest and thickest tendon in the body.",
    "Trendelenburg sign results from weak gluteus medius and minimus.",
    "The hip joint gains stability from a deep acetabulum and strong iliofemoral ligament.",
    "The iliofemoral ligament is the strongest ligament in the body.",
    "Adductor canal transmits the femoral artery, vein and saphenous nerve.",
    "The dorsalis pedis pulse is felt lateral to the extensor hallucis longus tendon.",
    "Plantar fasciitis is inflammation of the plantar aponeurosis near the calcaneus.",
    "The arches of the foot distribute body weight and act as shock absorbers.",
    "Quadriceps femoris has four heads and extends the knee.",
    "The popliteal fossa contains the popliteal artery, vein and tibial nerve.",
    "Screw-home movement locks the knee in full extension.",
    "The tibial nerve supplies the posterior compartment of the leg.",
    "Compartment syndrome most commonly affects the anterior compartment of the leg.",
  ],
  Thorax: [
    "The heart beats around 100,000 times each day.",
    "There are 12 pairs of ribs; ribs 11 and 12 are floating ribs.",
    "The right lung has three lobes; the left has two plus a lingula.",
    "The left lung has a cardiac notch to accommodate the heart.",
    "The diaphragm is the main muscle of inspiration, supplied by the phrenic nerve (C3,4,5).",
    "C3, 4, 5 keep the diaphragm alive.",
    "The IVC passes through the diaphragm at the T8 level.",
    "The oesophagus pierces the diaphragm at T10, the aorta at T12.",
    "The right main bronchus is wider, shorter and more vertical — aspiration goes right.",
    "The pericardium has fibrous and serous layers; the serous layer has two sheets.",
    "Cardiac tamponade compresses the heart and reduces venous filling.",
    "The SA node is the natural pacemaker at about 60–100 beats per minute.",
    "Coronary arteries fill during diastole, not systole.",
    "The left anterior descending artery is nicknamed the 'widow-maker'.",
    "Intercostal neurovascular bundles run in the costal groove — VAN from above down.",
    "Chest drains are inserted above the rib to avoid the neurovascular bundle.",
    "The thoracic duct drains lymph from the whole body except the right upper quadrant.",
    "The mediastinum is divided into superior and inferior (anterior, middle, posterior) parts.",
    "The trachea bifurcates at the sternal angle (T4/T5) at the carina.",
    "The sternal angle of Louis is a key surface landmark at the 2nd costal cartilage.",
    "The apex beat is normally felt in the 5th intercostal space, mid-clavicular line.",
    "Pleural fluid volume is only about 15 ml but allows frictionless lung movement.",
    "The azygos vein drains posterior thoracic walls into the SVC.",
    "The thymus is large in children and largely replaced by fat in adults.",
  ],
  Abdomen: [
    "The small intestine is around 6 metres long in adults.",
    "The stomach lining is replaced roughly every 3–5 days.",
    "The liver performs over 500 known functions.",
    "The liver receives 75% of its blood from the portal vein.",
    "The spleen is the largest lymphoid organ and a graveyard for old red cells.",
    "McBurney's point marks the surface projection of the appendix base.",
    "The appendix position is most commonly retrocaecal.",
    "The inguinal canal is about 4 cm long and lies above the inguinal ligament.",
    "Indirect inguinal hernias pass lateral to the inferior epigastric vessels.",
    "The rectus sheath differs above and below the arcuate line.",
    "The greater omentum is called the 'abdominal policeman' for walling off infection.",
    "Peritoneum has a parietal layer with somatic pain fibres and a visceral layer without.",
    "Referred pain to the shoulder tip suggests diaphragmatic irritation (C4).",
    "The portal vein is formed by the splenic and superior mesenteric veins.",
    "Porto-systemic anastomoses cause oesophageal varices and caput medusae.",
    "The kidneys filter about 180 litres of plasma per day.",
    "The right kidney sits slightly lower because of the liver.",
    "The ureter is narrowest at the pelvi-ureteric junction, pelvic brim and vesico-ureteric junction.",
    "The adrenal cortex and medulla have different embryological origins.",
    "The duodenum is retroperitoneal except for its first 2.5 cm.",
    "The gallbladder fundus lies at the tip of the 9th costal cartilage.",
    "Calot's triangle is bounded by the cystic duct, common hepatic duct and liver.",
    "Meckel's diverticulum follows the rule of 2s: 2% of people, 2 feet from the ileocaecal valve, 2 inches long.",
    "The pancreas is retroperitoneal except for the tail in the splenorenal ligament.",
  ],
  Pelvis: [
    "The female pelvis is wider and shallower than the male pelvis for childbirth.",
    "The pelvic diaphragm is formed mainly by levator ani and coccygeus.",
    "The pudendal nerve (S2,3,4) keeps the pelvic floor off the floor.",
    "The perineum is divided into urogenital and anal triangles.",
    "The ischioanal fossa is a common site for abscess formation.",
    "The prostate has five lobes; the median lobe enlarges in BPH.",
    "The uterus is normally anteverted and anteflexed.",
    "The ureter passes under the uterine artery — 'water under the bridge'.",
    "The rectouterine pouch of Douglas is the lowest point in the female peritoneal cavity.",
    "The obturator nerve arises from L2–L4 and supplies the medial thigh.",
    "The sacrum is formed by five fused vertebrae.",
    "The pelvic brim separates the false (greater) from the true (lesser) pelvis.",
    "The internal iliac artery supplies most pelvic viscera.",
    "The external anal sphincter is under voluntary control by the pudendal nerve.",
    "The broad ligament is a peritoneal fold, not a true supporting ligament.",
    "Ovarian arteries arise directly from the abdominal aorta at L2.",
    "The bladder in adults is a pelvic organ but rises into the abdomen when full.",
  ],
  "Head & Neck": [
    "The human skull is made up of 22 bones, 8 cranial and 14 facial.",
    "The mandible is the only mobile bone of the skull.",
    "The temporomandibular joint is a synovial joint with an articular disc.",
    "There are 12 pairs of cranial nerves.",
    "The facial nerve gives 'Ten Zebras Bit My Cheeks' branches within the parotid.",
    "The parotid gland is pierced by the facial nerve, retromandibular vein and external carotid artery.",
    "The trigeminal nerve has ophthalmic, maxillary and mandibular divisions.",
    "The thyroid gland moves with swallowing because of the pretracheal fascia.",
    "The recurrent laryngeal nerve supplies all intrinsic laryngeal muscles except cricothyroid.",
    "The carotid sinus contains baroreceptors that monitor blood pressure.",
    "The carotid body is a chemoreceptor sensing oxygen tension.",
    "The danger area of the face drains to the cavernous sinus via the ophthalmic veins.",
    "The tongue's anterior two-thirds get taste from chorda tympani.",
    "All tongue muscles are supplied by the hypoglossal nerve except palatoglossus.",
    "The eye's superior oblique is supplied by the trochlear nerve (SO4).",
    "LR6 SO4 AO3: lateral rectus by CN VI, superior oblique by CN IV, the rest by CN III.",
    "The cavernous sinus transmits CN III, IV, V1, V2 and VI plus the internal carotid.",
    "The pterion is the thinnest part of the skull and overlies the middle meningeal artery.",
    "The middle ear contains the malleus, incus and stapes.",
    "The Eustachian tube equalises middle ear pressure with the nasopharynx.",
    "Waldeyer's ring is a lymphoid ring guarding the pharynx.",
    "Sternocleidomastoid divides the neck into anterior and posterior triangles.",
    "The scalp has five layers: SCALP — skin, connective tissue, aponeurosis, loose tissue, pericranium.",
    "Nasal sinuses are the frontal, maxillary, ethmoidal and sphenoidal.",
    "The maxillary sinus drains at a high point, so it drains poorly when upright.",
  ],
  Neuroanatomy: [
    "The brain contains roughly 86 billion neurons.",
    "The brain uses about 20% of the body's oxygen and energy at rest.",
    "The spinal cord ends at L1/L2 in adults as the conus medullaris.",
    "Lumbar puncture is done at L3/L4 to avoid the spinal cord.",
    "The cauda equina is a bundle of nerve roots below the conus medullaris.",
    "There are three meninges: dura, arachnoid and pia mater.",
    "CSF total volume is about 150 ml and is replaced 3–4 times a day.",
    "CSF is produced by the choroid plexus in the ventricles.",
    "The circle of Willis provides collateral circulation to the brain.",
    "Broca's area governs speech production; Wernicke's area governs comprehension.",
    "The corpus callosum contains about 200 million axons linking the hemispheres.",
    "The cerebellum holds more neurons than the rest of the brain combined.",
    "The blood-brain barrier is formed by tight junctions of capillary endothelium.",
    "The internal capsule carries corticospinal fibres in its posterior limb.",
    "Decussation of the pyramids explains contralateral motor control.",
    "The dorsal column carries fine touch, vibration and proprioception.",
    "The spinothalamic tract carries pain and temperature.",
    "The hippocampus is essential for forming new declarative memories.",
    "The hypothalamus links the nervous and endocrine systems.",
    "The substantia nigra degenerates in Parkinson's disease.",
    "Grey matter is outside in the brain and inside in the spinal cord.",
    "Myelination speeds conduction by saltatory transmission at nodes of Ranvier.",
    "The vagus nerve is the longest cranial nerve, reaching the abdomen.",
  ],
  Histology: [
    "Epithelium is avascular and relies on the underlying connective tissue for nutrients.",
    "Simple squamous epithelium lines alveoli for rapid gas exchange.",
    "Pseudostratified ciliated columnar epithelium lines the trachea.",
    "Transitional epithelium (urothelium) stretches to line the bladder.",
    "Goblet cells secrete mucus and are unicellular glands.",
    "Skeletal muscle fibres are multinucleated with peripheral nuclei.",
    "Cardiac muscle has intercalated discs allowing synchronised contraction.",
    "Smooth muscle cells are spindle-shaped with a single central nucleus.",
    "Osteons (Haversian systems) are the structural units of compact bone.",
    "Osteoclasts are multinucleated cells that resorb bone.",
    "Chondrocytes sit in lacunae within a cartilage matrix.",
    "Adipose tissue stores energy and insulates; brown fat generates heat.",
    "Elastic fibres in arteries allow recoil and maintain diastolic pressure.",
    "Reticular fibres form the scaffolding of lymphoid organs.",
    "The liver lobule is hexagonal with a central vein and portal triads at the corners.",
    "Kupffer cells are resident macrophages of the liver sinusoids.",
    "Renal corpuscle = glomerulus plus Bowman's capsule.",
    "Podocytes wrap glomerular capillaries with filtration slits.",
    "Peyer's patches are lymphoid aggregates in the ileum.",
    "Merocrine, apocrine and holocrine describe glandular secretion modes.",
    "Sebaceous glands are holocrine — the whole cell becomes the secretion.",
    "Spermatogenesis takes about 64–74 days in seminiferous tubules.",
  ],
  Embryology: [
    "Fertilisation normally occurs in the ampulla of the uterine tube.",
    "Implantation happens around day 6–7 after fertilisation.",
    "The trilaminar disc forms during gastrulation in week 3.",
    "Ectoderm gives rise to skin and the nervous system.",
    "Mesoderm forms muscle, bone, blood and the urogenital system.",
    "Endoderm lines the gut tube and forms its derivatives.",
    "The neural tube closes between days 22 and 28.",
    "Failure of neural tube closure causes spina bifida or anencephaly.",
    "Folic acid supplementation reduces neural tube defects.",
    "The heart is the first functional organ, beating around day 22.",
    "The embryonic period is weeks 3–8, the most vulnerable to teratogens.",
    "Pharyngeal arches give rise to structures of the head and neck.",
    "The first pharyngeal arch is supplied by the trigeminal nerve.",
    "The thyroid gland descends from the foramen caecum of the tongue.",
    "A thyroglossal cyst arises from a persistent thyroglossal duct.",
    "The midgut herniates physiologically at week 6 and returns by week 10.",
    "Midgut rotates 270° counterclockwise around the superior mesenteric artery.",
    "The ductus arteriosus becomes the ligamentum arteriosum after birth.",
    "The foramen ovale closes at birth to become the fossa ovalis.",
    "The umbilical vein becomes the ligamentum teres of the liver.",
    "The urachus remnant is the median umbilical ligament.",
    "Testes descend into the scrotum during the 7th–9th month.",
    "The diaphragm develops from four structures including the septum transversum.",
    "Cleft lip results from failed fusion of the maxillary and medial nasal processes.",
  ],
};

function buildFacts(): AnatomyFact[] {
  const entries = Object.entries(BY_TOPIC).map(([topic, list]) => ({ topic, list }));
  const out: AnatomyFact[] = [];
  const max = Math.max(...entries.map((e) => e.list.length));
  // Interleave topics so consecutive days rotate through different regions.
  for (let i = 0; i < max; i++) {
    for (const e of entries) {
      if (i < e.list.length) out.push({ id: out.length + 1, fact: e.list[i], topic: e.topic });
    }
  }
  return out;
}

export const ANATOMY_FACTS: AnatomyFact[] = buildFacts();

export function dayOfYear(date = new Date()): number {
  const start = Date.UTC(date.getFullYear(), 0, 0);
  const now = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
  return Math.floor((now - start) / 86_400_000);
}

export function getDailyFact(date = new Date()): AnatomyFact {
  return ANATOMY_FACTS[dayOfYear(date) % ANATOMY_FACTS.length];
}
